### ISSUE TITLE
Please follow standard file-naming conventions

### ISSUE THREAD

**Issue by gmosx** [kelvin13/noise#2]
It would be great if you could follow standard SPM conventions, e.g.

sources -> Sources
tests -> Tests
readme.md -> README.md

**Comment by tayloraswift** [comment]
any particular reason to switch to SPM 3 capitalized names? If i remember right Noise uses Swift 4 features so it shouldn’t build with the Swift 3 toolchain anyway

also SPM doesn’t recognize readme files
